language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install flake8
  - pip install python-coveralls

before_script:
  - flake8 pyalpa/

script:
  - nosetests --with-coverage -v

after_success:
  - coveralls
